name: CI

on:
  push:
    branches:
      - main

env:
  SHOWVOC_PASSWORD: ${{ secrets.SHOWVOC_PASSWORD }}

jobs:
  sync-to-showvoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Synchronize ShowVoc projects
        run: .github/workflows/scripts/synchronize.sh
